"""phase2 schema

Revision ID: 3afa7725dcf6
Revises: 
Create Date: 2026-03-12 22:52:16.417930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afa7725dcf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date')
    )
    op.create_index(op.f('ix_fund_nav_date'), 'fund_nav', ['date'], unique=False)
    op.create_index(op.f('ix_fund_nav_ticker'), 'fund_nav', ['ticker'], unique=False)
    op.create_table('fund_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('returns_1y', sa.Float(), nullable=True),
    sa.Column('returns_3y', sa.Float(), nullable=True),
    sa.Column('returns_5y', sa.Float(), nullable=True),
    sa.Column('benchmark_returns_1y', sa.Float(), nullable=True),
    sa.Column('benchmark_returns_3y', sa.Float(), nullable=True),
    sa.Column('benchmark_returns_5y', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('ter', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('fund_type', sa.String(length=30), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=20), nullable=True),
    sa.Column('benchmark_name', sa.String(length=100), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('return_1y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('indicator_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('indicator_id', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series_key', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'indicator_id', 'interval', 'date', 'series_key')
    )
    op.create_index(op.f('ix_indicator_data_date'), 'indicator_data', ['date'], unique=False)
    op.create_index(op.f('ix_indicator_data_ticker'), 'indicator_data', ['ticker'], unique=False)
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('daily_change', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('ohlcv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', 'interval')
    )
    op.create_index(op.f('ix_ohlcv_data_date'), 'ohlcv_data', ['date'], unique=False)
    op.create_index(op.f('ix_ohlcv_data_ticker'), 'ohlcv_data', ['ticker'], unique=False)
    op.create_table('signal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('indicator_id', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'indicator_id')
    )
    op.create_index(op.f('ix_signal_data_ticker'), 'signal_data', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_data_ticker'), table_name='signal_data')
    op.drop_table('signal_data')
    op.drop_index(op.f('ix_ohlcv_data_ticker'), table_name='ohlcv_data')
    op.drop_index(op.f('ix_ohlcv_data_date'), table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_table('indices')
    op.drop_index(op.f('ix_indicator_data_ticker'), table_name='indicator_data')
    op.drop_index(op.f('ix_indicator_data_date'), table_name='indicator_data')
    op.drop_table('indicator_data')
    op.drop_table('funds')
    op.drop_table('fund_performance')
    op.drop_index(op.f('ix_fund_nav_ticker'), table_name='fund_nav')
    op.drop_index(op.f('ix_fund_nav_date'), table_name='fund_nav')
    op.drop_table('fund_nav')
    # ### end Alembic commands ###
